version: '3.7'
services:
  mongodb-Cont:
    image: mongo:latest
    container_name: mongodb-cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - .dbdata:/data/db

# version: '3'
# services:
#   mongodb:
#     image: mongo:latest
#     container_name: my-mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: adminpassword
# volumes:
#   mongodb_data:
